routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function(){
    Route::resource('products', 'ProductController');
    Route::resource('article', 'ArticleController');
    Route::resource('posts', 'PostController');
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected  $fillable = ['title', 'content'];
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;


use App\Article;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::all();
        return view('article.index',compact('articles'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('article.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Article::create($request->all());
        return redirect('/article');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::find($id);
        return view('article.edit', compact('article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $article = Article::find($id);
        $article->update($request->all());
        return redirect('/article');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Article::destroy($id);
        return redirect('/article');
    }
}

resources/views/article/create.blade.php
@extends('layouts.app')
@section('content')
<form action="{{route('article.store')}}" method="post" class="w-50 mx-auto alert">
    {{csrf_field()}}
    <input type="text" placeholder="Title" name="title" class="form-control">
    <textarea name="content" id="" cols="30" rows="10" placeholder="Content" class="form-control"></textarea>
    <button class="btn btn-success">Create</button>
</form>
@endsection

resources/views/article/edit.blade.php
@extends('layouts.app')
@section('content')

    <form action="{{route('article.update',$article->id)}}" method="post" class="w-50 mx-auto alert">
        {{csrf_field()}}
        {{ method_field('PUT')}}
        <input type="text" placeholder="{{$article->title}}" name="title" class="form-control">
        <textarea name="content" id="" cols="30" rows="10" placeholder="{{$article->content}}" class="form-control"></textarea>
        <button class="btn btn-success">Update</button>
    </form>

@endsection

resources/views/article/index.blade.php
@extends('layouts.app')
@section('content')
    <table class="table">
        <tr>
            <th>Title</th>
            <th>Content</th>
            <th>Action</th>
        </tr>
        @foreach($articles as $item)
            <tr>
                <td>{{$item->title}}</td>
                <td>{{$item->content}}
                <td>
                    <div class="d-flex">
                        <a href="{{route('article.edit',$item->id)}}" type="button" class="btn btn-success">Edit</a>
                        <form action="{{route('article.destroy',$item->id)}}" method="post">
                            {{csrf_field()}}
                            {{ method_field('DELETE') }}
                            <button class="btn btn-danger">Delete</button>
                        </form>
                    </div>
                </td>
            </tr>
        @endforeach

    </table>



@endsection