routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function(){
    Route::resource('products', 'ProductController');
    Route::resource('article', 'ArticleController');
    Route::resource('posts', 'PostController');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected  $fillable = ['title', 'context'];
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;
use function Sodium\compare;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $search = $request->get('search', '');
        if(!$search){$search = '';}
        $order = $request->get('order');
        if(!$order){$order = 'asc';}

        $posts = Post::where('title', 'LIKE', "%$search%")->orderby('title', $order)->paginate(3);
        return view('posts.index', compact('posts'), compact('search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Post::create($request->all());

        return redirect('/posts');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);
        return view('posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);
        return view('posts.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post = Post::find($id);
        $post->update($request->all());
        return redirect('/posts');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Post::destroy($id);
        return redirect('/posts');
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Post</div>
                    <div class="card-body">
                        <form action="/posts" method="post" enctype="multipart/form-data">
                            @csrf
                            <input type="text" name="title" placeholder="Title" class="form-control">
                            <textarea name="context" placeholder="Context" cols="30" rows="10" class="form-control"></textarea>
                            <input type="submit" class="btn btn-success" value="Create">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Post</div>
                    <div class="card-body">
                        <form action="{{route('posts.update', $post->id )}}" method="post" enctype="multipart/form-data">
                            @csrf
                            {{method_field('patch')}}
                            <input type="text" name="title" placeholder="Name" value="{{$post->title}}" class="form-control">
                            <textarea name="context" placeholder="Description" cols="30" rows="10" class="form-control">{{$post->context}}</textarea>
                            <input type="submit" class="btn btn-success" value="Update">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">

                    <div class="card-header">Post
                        <a href="/posts/create" class="btn btn-primary float-right">Add new</a>
                    </div>

                    <div class="card-header">
                        <form action="/posts" method="get">
                            <input type="search" name="search" class="form-control" value="{{$search}}"><br>
                            <select  name="order" class="form-control">
                                <option value="asc">
                                    Order By Title
                                </option>
                                <option value="desc">
                                    Order By Title desc
                                </option>
                            </select>
                            <button class="btn btn-success">Search</button>
                        </form>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <tr>
                                <th>Title</th>
                                <th>Context</th>
                            </tr>
                            @foreach($posts as $item)
                                <tr>
                                    <td>{{$item->title}}</td>
                                    <td>{{$item->context}}</td>
                                    <td>
                                        <div class="d-flex">
                                            <a href="/posts/{{$item->id}}" class="btn btn-primary">Show</a>
                                            <a href="{{route('posts.edit', $item->id)}}" class="btn btn-success">Edit</a>
                                            <form action="{{route('posts.destroy', $item->id)}}" method="post">
                                                @csrf
                                                {{method_field('DELETE')}}
                                                <button class="btn btn-danger" >Delete</button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                        {{ $posts->appends(Request::except('page'))->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Post</div>
                    <div class="card-body">
                        <table class="table">
                            <tr>
                                <th>Title</th>
                                <td>{{$post->title}}</td>
                            </tr>
                            <tr>
                                <th>Context</th>
                                <td>{{$post->context}}</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection