routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function(){
    Route::resource('products', 'ProductController');
    Route::resource('article', 'ArticleController');
    Route::resource('posts', 'PostController');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected  $fillable = ['name', 'description', 'price', 'image'];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $search = $request->get('search', '');
        $price_from = $request->get('price_from', 0);
        $max_price = Product::max('price');
        $price_to = $request->get('price_to', $max_price);
        $products = Product::where('name', 'LIKE', "%$search%")->whereBetween('price', [$price_from, $price_to])
            ->orwhere('description', 'LIKE', "%$search%")
            ->whereBetween('price', [$price_from, $price_to])->orderBy('price', 'desc')->paginate(10);;


        return view('products.index', compact('products', 'search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Product::create($request->all());

        return redirect('/products');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('products.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        return view('products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);
        $product->update($request->all());
        return redirect('/products');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::destroy($id);
        return redirect('/products');
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Products</div>

                    <div class="card-body">


                        <form action="/products" method="post" enctype="multipart/form-data">
                            @csrf
                            <input type="text" name="name" placeholder="Name" class="form-control">
                            <textarea name="description" placeholder="Description" cols="30" rows="10" class="form-control"></textarea>
                            <input type="number" name="price" placeholder="Price" class="form-control">
                            <input type="file" name="image" class="form-control">
                            <input type="submit" class="btn btn-success" value="Create">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Products</div>

                    <div class="card-body">


                        <form action="{{route('products.update', $product->id)}}" method="post" enctype="multipart/form-data">
                            @csrf
                            {{method_field('patch')}}
                            <input type="text" name="name" placeholder="Name" value="{{$product->name}}" class="form-control">
                            <textarea name="description" placeholder="Description" cols="30" rows="10" class="form-control">{{$product->description}}</textarea>
                            <input type="number" name="price" placeholder="Price" class="form-control" value="{{$product->price}}">
                            <input type="file" name="image" class="form-control">
                            <input type="submit" class="btn btn-success" value="Update">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/products/index.blade.php
@extends('layouts.app')
@section('content')
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">Products <a href="/products/create" class="btn btn-primary float-right">Add new</a></div>

                        <div class="card-body">

                            <form action="/products" method="get">
                                <input type="search" name="search" class="form-control" value="{{$search}}">
                                <div class="d-flex">
                                <input type="number" name="price_from" class="form-control">
                                <input type="number" name="price_to" class="form-control">
                                </div>
                                <button class="btn btn-success">Search</button>
                            </form>

                            <table class="table">
                                <tr>
                                    <th>Name</th>
                                    <th>Price</th>
                                    <th>Actions</th>
                                </tr>
                                @foreach($products as $item)
                                    <tr>
                                        <td>{{$item->name}}</td>
                                        <td>{{$item->price}}</td>
                                        <td>
                                            <div class="d-flex">
                                                <a href="/products/{{$item->id}}" class="btn btn-primary">Show</a>
                                                <a href="{{route('products.edit', $item->id)}}" class="btn btn-success">Edit</a>
                                                <form action="{{route('products.destroy', $item->id)}}" method="post">
                                                    @csrf
                                                    {{method_field('DELETE')}}
                                                    <button class="btn btn-danger" >Delete</button>
                                                </form>
                                            </div>

                                        </td>
                                    </tr>
                                    @endforeach
                            </table>
                            {{$products->links()}}
                        </div>
                    </div>
                </div>
            </div>
        </div>

@endsection

resources/views/products/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Products</div>

                    <div class="card-body">


                        <table class="table">
                            <tr>
                                <th>Name</th>
                                <td></td>
                            </tr>
                            <tr>
                                <th>Description</th>
                                <td></td>
                            </tr>
                            <tr>
                                <th>Price</th>
                                <td></td>
                            </tr>
                            <tr>
                                <th>Image</th>
                                <td></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection